# features/sets/v3_New_Dawn/registry.py

"""
Feature registry for feature set 'v3_New_Dawn'.

Maps feature names (as used in YAML configs) to feature-extraction functions
defined in technical.py.
"""

# Import feature functions from technical.py
from features.sets.v3_New_Dawn.technical import (
    # Block ML-1.1: Price & Normalization
    feature_price,
    feature_price_log,
    feature_price_vs_ma200,
    feature_close_position_in_range,
    # Block ML-1.2: Returns
    feature_log_return_1d,
    feature_daily_return,
    feature_gap_pct,
    feature_weekly_return_5d,
    feature_monthly_return_21d,
    feature_quarterly_return_63d,
    feature_ytd_return,
    feature_weekly_return_1w,
    # Block ML-1.3: 52-Week Position
    feature_dist_52w_high,
    feature_dist_52w_low,
    feature_pos_52w,
    # Block ML-1.4: Basic Moving Averages
    feature_sma20_ratio,
    feature_sma50_ratio,
    feature_sma200_ratio,
    feature_ema20_ratio,
    feature_ema50_ratio,
    feature_ema200_ratio,
    feature_sma20_sma50_ratio,
    feature_sma50_sma200_ratio,
    # Block ML-1.5: MA Slopes
    feature_sma20_slope,
    feature_sma50_slope,
    feature_sma200_slope,
    feature_ema20_slope,
    # Block ML-1.6: Basic Volatility
    feature_volatility_5d,
    feature_volatility_21d,
    feature_atr14_normalized,
    # Block ML-2.1: Basic Volume
    feature_log_volume,
    feature_log_avg_volume_20d,
    feature_relative_volume,
    feature_obv_momentum,
    feature_volume_trend,
    feature_volume_momentum,
    # Block ML-2.2: RSI Family
    feature_rsi7,
    feature_rsi14,
    feature_rsi21,
    feature_rsi_momentum,
    # Block ML-2.3: MACD Family
    feature_macd_line,
    feature_macd_signal,
    feature_macd_histogram_normalized,
    feature_macd_momentum,
    # Block ML-2.4: ROC Family
    feature_roc5,
    feature_roc10,
    feature_roc20,
    feature_momentum_10d,
    # Block ML-2.5: Stochastic Family
    feature_stochastic_k14,
    feature_stochastic_d14,
    feature_stochastic_oscillator,
    # Block ML-2.6: Other Oscillators
    feature_cci20,
    feature_williams_r14,
    feature_ppo_histogram,
    feature_dpo,
    feature_kama_slope,
    feature_chaikin_money_flow,
    feature_mfi,
    feature_tsi,
    feature_trend_residual,
    # Block ML-3.1: Additional Momentum Oscillators
    feature_ultimate_oscillator,
    feature_awesome_oscillator,
    feature_momentum_20d,
    feature_momentum_50d,
    # Block ML-3.2: Momentum Quality Features
    feature_momentum_divergence,
    feature_momentum_consistency,
    feature_momentum_acceleration,
    feature_momentum_strength,
    feature_momentum_persistence,
    feature_momentum_exhaustion,
    feature_momentum_reversal_signal,
    feature_momentum_cross,
    feature_momentum_rank,
    feature_momentum_regime,
    # Block ML-3.3: Additional Momentum Variants
    feature_momentum_5d,
    feature_momentum_15d,
    feature_momentum_30d,
    feature_momentum_vs_price,
    # Block ML-4.1: Volatility Regime Detection
    feature_volatility_regime,
    feature_volatility_trend,
    feature_bb_squeeze,
    feature_bb_expansion,
    feature_atr_ratio_20d,
    feature_atr_ratio_252d,
    feature_volatility_percentile_20d,
    feature_volatility_percentile_252d,
    feature_high_volatility_flag,
    feature_low_volatility_flag,
    # Block ML-4.2: Advanced Volatility Estimators
    feature_parkinson_volatility,
    feature_garman_klass_volatility,
    feature_rogers_satchell_volatility,
    feature_yang_zhang_volatility,
    feature_volatility_clustering,
    # Block ML-4.3: Realized Volatility
    feature_realized_volatility_5d,
    feature_realized_volatility_20d,
    feature_volatility_regime_change,
    # Block ML-5.1: ADX & Trend Strength
    feature_adx14,
    feature_adx20,
    feature_adx50,
    feature_trend_strength_20d,
    feature_trend_strength_50d,
    # Block ML-5.2: MA Alignment & Crossovers
    feature_ema_alignment,
    feature_ma_crossover_bullish,
    feature_ma_crossover_bearish,
    feature_price_vs_all_mas,
    feature_sma_slope_20d,
    feature_sma_slope_50d,
    # Block ML-5.3: EMA Slopes
    feature_ema_slope_20d,
    feature_ema_slope_50d,
    # Block ML-5.4: Trend Quality Features
    feature_trend_consistency,
    feature_trend_duration,
    feature_trend_reversal_signal,
    feature_trend_acceleration,
    feature_trend_divergence,
    feature_trend_pullback_strength,
    feature_trend_breakout_strength,
    feature_trend_following_strength,
    feature_trend_regime,
    # Block ML-6.1: Support/Resistance Levels
    feature_resistance_level_20d,
    feature_resistance_level_50d,
    feature_resistance_level_100d,
    feature_support_level_20d,
    feature_support_level_50d,
    feature_support_level_100d,
    # Block ML-6.2: Distance to S/R
    feature_distance_to_resistance,
    feature_distance_to_support,
    feature_price_near_resistance,
    feature_price_near_support,
    # Block ML-6.3: S/R Strength
    feature_resistance_touches,
    feature_support_touches,
    feature_support_resistance_strength,
    feature_donchian_position,
    # Block ML-6.4: Pivot & Fibonacci
    feature_pivot_point,
    feature_pivot_resistance_1,
    feature_pivot_support_1,
    feature_fibonacci_retracement,
    # Block ML-7.1: Volume Profile Approximations
    feature_volume_profile_poc,
    feature_volume_profile_vah,
    feature_volume_profile_val,
    feature_price_vs_poc,
    feature_price_vs_vah,
    feature_price_vs_val,
    # Block ML-7.2: VWAP Features
    feature_volume_weighted_price,
    feature_price_vs_vwap,
    feature_vwap_slope,
    feature_vwap_distance_pct,
    feature_volume_profile_width,
    # Block ML-7.3: Volume Analysis
    feature_volume_distribution,
    feature_volume_climax,
    feature_volume_dry_up,
    feature_volume_breakout,
    feature_volume_divergence,
    feature_volume_autocorrelation,
    feature_volume_imbalance,
    feature_volume_at_price,
    feature_volatility_ratio,
    # Block ML-8.1: Weekly Returns
    feature_weekly_return_2w,
    feature_weekly_return_4w,
    feature_weekly_volume_ratio,
    # Block ML-8.2: Weekly Moving Averages
    feature_weekly_sma_5w,
    feature_weekly_sma_10w,
    feature_weekly_sma_20w,
    feature_weekly_ema_5w,
    feature_weekly_ema_10w,
    feature_weekly_ema_20w,
    # Block ML-8.3: Weekly Indicators
    feature_weekly_rsi_14w,
    feature_weekly_rsi_7w,
    feature_weekly_macd_histogram,
    feature_weekly_macd_signal,
    feature_weekly_adx,
    feature_weekly_stochastic,
    # Block ML-8.4: Weekly Price Comparisons
    feature_close_vs_weekly_sma20,
    feature_close_vs_weekly_ema20,
    feature_weekly_atr_pct,
    feature_weekly_trend_strength,
    feature_weekly_momentum,
    # Block ML-9: Multi-Timeframe Monthly Features
    feature_monthly_return_1m,
    feature_monthly_return_3m,
    feature_monthly_sma_3m,
    feature_monthly_sma_6m,
    feature_monthly_rsi,
    # Block ML-10.1: Candlestick Components
    feature_candle_body_pct,
    feature_candle_upper_wick_pct,
    feature_candle_lower_wick_pct,
    feature_candle_wicks_ratio,
    # Block ML-10.2: Reversal Patterns
    feature_hanging_man,
    feature_inverted_hammer,
    feature_piercing_pattern,
    feature_dark_cloud_cover,
    feature_harami_bullish,
    feature_harami_bearish,
    feature_engulfing_bullish,
    feature_engulfing_bearish,
    # Block ML-10.3: Continuation Patterns
    feature_three_white_soldiers,
    feature_three_black_crows,
    feature_inside_bar,
    feature_outside_bar,
    feature_engulfing_strength,
    # Block ML-10.4: Single Candle Patterns
    feature_doji,
    feature_hammer,
    feature_shooting_star,
    feature_marubozu,
    feature_spinning_top,
    # Block ML-10.5: Pattern Quality
    feature_pattern_strength,
    feature_pattern_confirmation,
    feature_pattern_divergence,
    # Block ML-11: Price Action - Consecutive Days & Swings
    feature_consecutive_green_days,
    feature_consecutive_red_days,
    feature_higher_high_10d,
    feature_higher_low_10d,
    feature_swing_low_10d,
    feature_pattern_cluster,
    # Block ML-12: Market Regime Indicators (SPY-based)
    feature_market_regime,
    feature_regime_strength,
    feature_regime_duration,
    feature_regime_change_probability,
    feature_trending_market_flag,
    feature_choppy_market_flag,
    feature_bull_market_flag,
    feature_bear_market_flag,
    feature_market_volatility_regime,
    feature_market_momentum_regime,
    feature_regime_transition,
    feature_regime_stability,
    feature_market_sentiment,
    feature_market_fear_greed,
    feature_regime_consistency,
    # Block ML-13: Market Direction Features (SPY-based)
    feature_market_direction,
    feature_market_direction_strength,
    feature_market_trend_alignment,
    feature_market_momentum,
    feature_market_volatility_context,
    feature_market_timing,
    feature_market_support_resistance,
    feature_market_regime_consistency,
    feature_market_sector_rotation,
    feature_market_breadth,
    feature_market_leadership,
    feature_market_sentiment_alignment,
    # Block ML-14: Relative Strength (SPY-based)
    feature_relative_strength_spy,
    feature_relative_strength_spy_50d,
    feature_rs_rank_20d,
    feature_rs_rank_50d,
    feature_rs_rank_100d,
    feature_rs_momentum,
    feature_outperformance_flag,
    feature_rs_vs_price,
    feature_rs_consistency,
    feature_rs_regime,
    feature_rs_trend,
    feature_relative_strength_sector,
    # Block ML-15: Time-Based Features (14 features, skipping days_since_earnings)
    feature_day_of_week,
    feature_day_of_week_sin,
    feature_day_of_week_cos,
    feature_day_of_month,
    feature_day_of_month_sin,
    feature_day_of_month_cos,
    feature_month_of_year,
    feature_month_of_year_sin,
    feature_month_of_year_cos,
    feature_quarter,
    feature_is_month_end,
    feature_is_quarter_end,
    feature_is_year_end,
    feature_trading_day_of_year,
    # Block ML-16: Statistical Features (15 features, volume_autocorrelation already exists)
    feature_price_skewness_20d,
    feature_price_kurtosis_20d,
    feature_returns_skewness_20d,
    feature_returns_kurtosis_20d,
    feature_price_autocorrelation_1d,
    feature_price_autocorrelation_5d,
    feature_returns_autocorrelation,
    # volume_autocorrelation already exists from earlier block
    feature_price_variance_ratio,
    feature_price_half_life,
    feature_returns_half_life,
    feature_price_stationarity,
    feature_returns_stationarity,
    feature_price_cointegration,
    feature_statistical_regime,
    # Block ML-17: Advanced Volatility Features (12 features)
    feature_volatility_skewness,
    feature_volatility_kurtosis,
    feature_volatility_autocorrelation,
    feature_volatility_mean_reversion,
    feature_volatility_of_volatility,
    feature_volatility_regime_persistence,
    feature_volatility_shock,
    feature_volatility_normalized_returns,
    feature_volatility_forecast,
    feature_volatility_term_structure,
    feature_volatility_risk_premium,
    feature_volatility_smoothness,
    # Block ML-18: Advanced Technical Indicators (8 features)
    feature_bollinger_band_width,
    feature_fractal_dimension_index,
    feature_hurst_exponent,
    feature_price_curvature,
    feature_aroon_up,
    feature_aroon_down,
    feature_aroon_oscillator,
    feature_donchian_breakout,
    # Block ML-19: Market Microstructure Proxies (8 features)
    feature_liquidity_measure,
    feature_price_impact_proxy,
    feature_bid_ask_spread_proxy,
    feature_order_flow_imbalance,
    feature_market_depth_proxy,
    feature_price_efficiency,
    feature_transaction_cost_proxy,
    feature_market_quality,
    # Block ML-20: Feature Interactions - Core (20 features)
    feature_rsi_x_volume,
    feature_rsi_x_atr,
    feature_macd_x_volume,
    feature_trend_x_momentum,
    feature_volume_x_momentum,
    feature_rsi_x_trend_strength,
    feature_volatility_x_volume,
    feature_volatility_x_trend,
    feature_trend_x_volatility,
    feature_volatility_x_regime_strength,
    feature_price_position_x_rsi,
    feature_support_resistance_x_momentum,
    feature_rsi_x_support_distance,
    feature_volume_x_breakout,
    feature_momentum_x_regime,
    feature_volume_x_regime,
    feature_rsi_x_relative_strength,
    feature_trend_x_relative_strength,
    feature_momentum_x_time,
    feature_volume_x_time,
    # Block ML-21: Predictive Gain Features (15 features)
    feature_historical_gain_probability,
    feature_gain_probability_score,
    feature_gain_regime,
    feature_gain_consistency,
    feature_gain_timing,
    feature_gain_momentum,
    feature_gain_acceleration,
    feature_target_distance,
    feature_gain_momentum_strength,
    feature_gain_breakout_signal,
    feature_gain_risk_ratio,
    feature_gain_volume_confirmation,
    feature_gain_trend_alignment,
    feature_gain_volatility_context,
    feature_gain_support_level,
    # Block ML-22: Accuracy-Enhancing Features (20 features)
    feature_signal_quality_score,
    feature_signal_strength,
    feature_signal_consistency,
    feature_signal_confirmation,
    feature_signal_timing,
    feature_signal_risk_reward,
    feature_signal_statistical_significance,
    feature_signal_historical_success,
    feature_signal_ensemble_score,
    feature_false_positive_risk,
    feature_signal_divergence,
    feature_signal_volume_confirmation,
    feature_signal_trend_alignment,
    feature_signal_volatility_context,
    feature_signal_regime_alignment,
    feature_signal_momentum_strength,
    feature_signal_support_resistance,
    feature_signal_relative_strength,
    feature_signal_multi_timeframe,
    feature_signal_pattern_confirmation,
    # Block ML-23: Market Context (SPY-based) (3 features)
    feature_mkt_spy_dist_sma200,
    feature_mkt_spy_sma200_slope,
    feature_beta_spy_252d,
    # Block ML-24: Breakout & Channel Features (2 new features, 2 already exist)
    feature_ttm_squeeze_on,
    feature_ttm_squeeze_momentum,
    # Block ML-25: Trend Exhaustion & Consolidation (4 features)
    feature_trend_consolidation,
    feature_trend_exhaustion,
    feature_trend_vs_mean_reversion,
    feature_volatility_jump,
    # Block ML-26.1: Enhanced Volatility Features (10 features)
    feature_volatility_forecast_accuracy,
    feature_volatility_forecast_error,
    feature_volatility_forecast_error_true,
    feature_volatility_forecast_trend,
    feature_volatility_clustering_strength,
    feature_volatility_regime_forecast,
    feature_volatility_surprise,
    feature_volatility_realized_forecast_ratio,
    # Block ML-26.2: Enhanced Gain Probability Features (5 features)
    feature_gain_probability_trend,
    feature_gain_probability_consistency_rank,
    feature_gain_probability_volatility_adjusted,
    # Block ML-26.3: Distance-Based Rank Features (5 features)
    feature_dist_support_rank,
    # Block ML-26.4: Percentile/Rank Features (8 features)
    feature_volatility_rank,
    feature_return_rank_3m,
    feature_momentum_rank_trend,
    # Block ML-26.5: Volatility-Volume Interactions (4 features)
    feature_volatility_volume_correlation,
    feature_volatility_volume_divergence,
    feature_volatility_forecast_volume_confirmation,
    # Block ML-26.6: Return-Volatility Interactions (3 features)
    feature_return_volatility_ratio,
    # Block ML-26.7: Regime Transition Features (3 features)
    feature_volatility_regime_transition_probability,
    feature_gain_regime_transition_probability,
    feature_momentum_regime_transition,
    # Block ML-26.8: Composite/Ensemble Features (6 features)
    feature_top_features_ensemble,
    feature_volatility_forecast_accuracy_weighted,
    feature_gain_probability_volatility_regime_interaction,
    # Block ML-27: Precision-Enhancing Features (5 features)
    feature_adr_percentage,
    feature_distance_from_monthly_vwap,
    feature_atr_channel_position,
    feature_vpt_divergence,
    feature_relative_strength_vs_sector,
)

# Feature registry mapping
FEATURE_REGISTRY = {
    # Block ML-1.1: Price & Normalization (4 features)
    'price': feature_price,
    'price_log': feature_price_log,
    'price_vs_ma200': feature_price_vs_ma200,
    'close_position_in_range': feature_close_position_in_range,
    # Block ML-1.2: Returns (8 features)
    'log_return_1d': feature_log_return_1d,
    'daily_return': feature_daily_return,
    'gap_pct': feature_gap_pct,
    'weekly_return_5d': feature_weekly_return_5d,
    'monthly_return_21d': feature_monthly_return_21d,
    'quarterly_return_63d': feature_quarterly_return_63d,
    'ytd_return': feature_ytd_return,
    'weekly_return_1w': feature_weekly_return_1w,
    # Block ML-1.3: 52-Week Position (3 features)
    'dist_52w_high': feature_dist_52w_high,
    'dist_52w_low': feature_dist_52w_low,
    'pos_52w': feature_pos_52w,
    # Block ML-1.4: Basic Moving Averages (8 features)
    'sma20_ratio': feature_sma20_ratio,
    'sma50_ratio': feature_sma50_ratio,
    'sma200_ratio': feature_sma200_ratio,
    'ema20_ratio': feature_ema20_ratio,
    'ema50_ratio': feature_ema50_ratio,
    'ema200_ratio': feature_ema200_ratio,
    'sma20_sma50_ratio': feature_sma20_sma50_ratio,
    'sma50_sma200_ratio': feature_sma50_sma200_ratio,
    # Block ML-1.5: MA Slopes (4 features)
    'sma20_slope': feature_sma20_slope,
    'sma50_slope': feature_sma50_slope,
    'sma200_slope': feature_sma200_slope,
    'ema20_slope': feature_ema20_slope,
    # Block ML-1.6: Basic Volatility (3 features)
    'volatility_5d': feature_volatility_5d,
    'volatility_21d': feature_volatility_21d,
    'atr14_normalized': feature_atr14_normalized,
    # Block ML-2.1: Basic Volume (6 features)
    'log_volume': feature_log_volume,
    'log_avg_volume_20d': feature_log_avg_volume_20d,
    'relative_volume': feature_relative_volume,
    'obv_momentum': feature_obv_momentum,
    'volume_trend': feature_volume_trend,
    'volume_momentum': feature_volume_momentum,
    # Block ML-2.2: RSI Family (4 features)
    'rsi7': feature_rsi7,
    'rsi14': feature_rsi14,
    'rsi21': feature_rsi21,
    'rsi_momentum': feature_rsi_momentum,
    # Block ML-2.3: MACD Family (4 features)
    'macd_line': feature_macd_line,
    'macd_signal': feature_macd_signal,
    'macd_histogram_normalized': feature_macd_histogram_normalized,
    'macd_momentum': feature_macd_momentum,
    # Block ML-2.4: ROC Family (4 features)
    'roc5': feature_roc5,
    'roc10': feature_roc10,
    'roc20': feature_roc20,
    'momentum_10d': feature_momentum_10d,
    # Block ML-2.5: Stochastic Family (3 features)
    'stochastic_k14': feature_stochastic_k14,
    'stochastic_d14': feature_stochastic_d14,
    'stochastic_oscillator': feature_stochastic_oscillator,
    # Block ML-2.6: Other Oscillators (9 features)
    'cci20': feature_cci20,
    'williams_r14': feature_williams_r14,
    'ppo_histogram': feature_ppo_histogram,
    'dpo': feature_dpo,
    'kama_slope': feature_kama_slope,
    'chaikin_money_flow': feature_chaikin_money_flow,
    'mfi': feature_mfi,
    'tsi': feature_tsi,
    'trend_residual': feature_trend_residual,
    # Block ML-3.1: Additional Momentum Oscillators (4 features)
    'ultimate_oscillator': feature_ultimate_oscillator,
    'awesome_oscillator': feature_awesome_oscillator,
    'momentum_20d': feature_momentum_20d,
    'momentum_50d': feature_momentum_50d,
    # Block ML-3.2: Momentum Quality Features (10 features)
    'momentum_divergence': feature_momentum_divergence,
    'momentum_consistency': feature_momentum_consistency,
    'momentum_acceleration': feature_momentum_acceleration,
    'momentum_strength': feature_momentum_strength,
    'momentum_persistence': feature_momentum_persistence,
    'momentum_exhaustion': feature_momentum_exhaustion,
    'momentum_reversal_signal': feature_momentum_reversal_signal,
    'momentum_cross': feature_momentum_cross,
    'momentum_rank': feature_momentum_rank,
    'momentum_regime': feature_momentum_regime,
    # Block ML-3.3: Additional Momentum Variants (4 features)
    'momentum_5d': feature_momentum_5d,
    'momentum_15d': feature_momentum_15d,
    'momentum_30d': feature_momentum_30d,
    'momentum_vs_price': feature_momentum_vs_price,
    # Block ML-4.1: Volatility Regime Detection (10 features)
    'volatility_regime': feature_volatility_regime,
    'volatility_trend': feature_volatility_trend,
    'bb_squeeze': feature_bb_squeeze,
    'bb_expansion': feature_bb_expansion,
    'atr_ratio_20d': feature_atr_ratio_20d,
    'atr_ratio_252d': feature_atr_ratio_252d,
    'volatility_percentile_20d': feature_volatility_percentile_20d,
    'volatility_percentile_252d': feature_volatility_percentile_252d,
    'high_volatility_flag': feature_high_volatility_flag,
    'low_volatility_flag': feature_low_volatility_flag,
    # Block ML-4.2: Advanced Volatility Estimators (5 features)
    'parkinson_volatility': feature_parkinson_volatility,
    'garman_klass_volatility': feature_garman_klass_volatility,
    'rogers_satchell_volatility': feature_rogers_satchell_volatility,
    'yang_zhang_volatility': feature_yang_zhang_volatility,
    'volatility_clustering': feature_volatility_clustering,
    # Block ML-4.3: Realized Volatility (3 features)
    'realized_volatility_5d': feature_realized_volatility_5d,
    'realized_volatility_20d': feature_realized_volatility_20d,
    'volatility_regime_change': feature_volatility_regime_change,
    # Block ML-5.1: ADX & Trend Strength (5 features)
    'adx14': feature_adx14,
    'adx20': feature_adx20,
    'adx50': feature_adx50,
    'trend_strength_20d': feature_trend_strength_20d,
    'trend_strength_50d': feature_trend_strength_50d,
    # Block ML-5.2: MA Alignment & Crossovers (6 features)
    'ema_alignment': feature_ema_alignment,
    'ma_crossover_bullish': feature_ma_crossover_bullish,
    'ma_crossover_bearish': feature_ma_crossover_bearish,
    'price_vs_all_mas': feature_price_vs_all_mas,
    'sma_slope_20d': feature_sma_slope_20d,
    'sma_slope_50d': feature_sma_slope_50d,
    # Block ML-5.3: EMA Slopes (2 features)
    'ema_slope_20d': feature_ema_slope_20d,
    'ema_slope_50d': feature_ema_slope_50d,
    # Block ML-5.4: Trend Quality Features (9 features)
    'trend_consistency': feature_trend_consistency,
    'trend_duration': feature_trend_duration,
    'trend_reversal_signal': feature_trend_reversal_signal,
    'trend_acceleration': feature_trend_acceleration,
    'trend_divergence': feature_trend_divergence,
    'trend_pullback_strength': feature_trend_pullback_strength,
    'trend_breakout_strength': feature_trend_breakout_strength,
    'trend_following_strength': feature_trend_following_strength,
    'trend_regime': feature_trend_regime,
    # Block ML-6.1: Support/Resistance Levels (6 features)
    'resistance_level_20d': feature_resistance_level_20d,
    'resistance_level_50d': feature_resistance_level_50d,
    'resistance_level_100d': feature_resistance_level_100d,
    'support_level_20d': feature_support_level_20d,
    'support_level_50d': feature_support_level_50d,
    'support_level_100d': feature_support_level_100d,
    # Block ML-6.2: Distance to S/R (4 features)
    'distance_to_resistance': feature_distance_to_resistance,
    'distance_to_support': feature_distance_to_support,
    'price_near_resistance': feature_price_near_resistance,
    'price_near_support': feature_price_near_support,
    # Block ML-6.3: S/R Strength (4 features)
    'resistance_touches': feature_resistance_touches,
    'support_touches': feature_support_touches,
    'support_resistance_strength': feature_support_resistance_strength,
    'donchian_position': feature_donchian_position,
    # Block ML-6.4: Pivot & Fibonacci (4 features)
    'pivot_point': feature_pivot_point,
    'pivot_resistance_1': feature_pivot_resistance_1,
    'pivot_support_1': feature_pivot_support_1,
    'fibonacci_retracement': feature_fibonacci_retracement,
    # Block ML-7.1: Volume Profile Approximations (6 features)
    'volume_profile_poc': feature_volume_profile_poc,
    'volume_profile_vah': feature_volume_profile_vah,
    'volume_profile_val': feature_volume_profile_val,
    'price_vs_poc': feature_price_vs_poc,
    'price_vs_vah': feature_price_vs_vah,
    'price_vs_val': feature_price_vs_val,
    # Block ML-7.2: VWAP Features (5 features)
    'volume_weighted_price': feature_volume_weighted_price,
    'price_vs_vwap': feature_price_vs_vwap,
    'vwap_slope': feature_vwap_slope,
    'vwap_distance_pct': feature_vwap_distance_pct,
    'volume_profile_width': feature_volume_profile_width,
    # Block ML-7.3: Volume Analysis (9 features)
    'volume_distribution': feature_volume_distribution,
    'volume_climax': feature_volume_climax,
    'volume_dry_up': feature_volume_dry_up,
    'volume_breakout': feature_volume_breakout,
    'volume_divergence': feature_volume_divergence,
    'volume_autocorrelation': feature_volume_autocorrelation,
    'volume_imbalance': feature_volume_imbalance,
    'volume_at_price': feature_volume_at_price,
    'volatility_ratio': feature_volatility_ratio,
    # Block ML-8.1: Weekly Returns (3 features)
    'weekly_return_2w': feature_weekly_return_2w,
    'weekly_return_4w': feature_weekly_return_4w,
    'weekly_volume_ratio': feature_weekly_volume_ratio,
    # Block ML-8.2: Weekly Moving Averages (6 features)
    'weekly_sma_5w': feature_weekly_sma_5w,
    'weekly_sma_10w': feature_weekly_sma_10w,
    'weekly_sma_20w': feature_weekly_sma_20w,
    'weekly_ema_5w': feature_weekly_ema_5w,
    'weekly_ema_10w': feature_weekly_ema_10w,
    'weekly_ema_20w': feature_weekly_ema_20w,
    # Block ML-8.3: Weekly Indicators (6 features)
    'weekly_rsi_14w': feature_weekly_rsi_14w,
    'weekly_rsi_7w': feature_weekly_rsi_7w,
    'weekly_macd_histogram': feature_weekly_macd_histogram,
    'weekly_macd_signal': feature_weekly_macd_signal,
    'weekly_adx': feature_weekly_adx,
    'weekly_stochastic': feature_weekly_stochastic,
    # Block ML-8.4: Weekly Price Comparisons (5 features)
    'close_vs_weekly_sma20': feature_close_vs_weekly_sma20,
    'close_vs_weekly_ema20': feature_close_vs_weekly_ema20,
    'weekly_atr_pct': feature_weekly_atr_pct,
    'weekly_trend_strength': feature_weekly_trend_strength,
    'weekly_momentum': feature_weekly_momentum,
    # Block ML-9: Multi-Timeframe Monthly Features (5 features)
    'monthly_return_1m': feature_monthly_return_1m,
    'monthly_return_3m': feature_monthly_return_3m,
    'monthly_sma_3m': feature_monthly_sma_3m,
    'monthly_sma_6m': feature_monthly_sma_6m,
    'monthly_rsi': feature_monthly_rsi,
    # Block ML-10.1: Candlestick Components (4 features)
    'candle_body_pct': feature_candle_body_pct,
    'candle_upper_wick_pct': feature_candle_upper_wick_pct,
    'candle_lower_wick_pct': feature_candle_lower_wick_pct,
    'candle_wicks_ratio': feature_candle_wicks_ratio,
    # Block ML-10.2: Reversal Patterns (8 features)
    'hanging_man': feature_hanging_man,
    'inverted_hammer': feature_inverted_hammer,
    'piercing_pattern': feature_piercing_pattern,
    'dark_cloud_cover': feature_dark_cloud_cover,
    'harami_bullish': feature_harami_bullish,
    'harami_bearish': feature_harami_bearish,
    'engulfing_bullish': feature_engulfing_bullish,
    'engulfing_bearish': feature_engulfing_bearish,
    # Block ML-10.3: Continuation Patterns (5 features)
    'three_white_soldiers': feature_three_white_soldiers,
    'three_black_crows': feature_three_black_crows,
    'inside_bar': feature_inside_bar,
    'outside_bar': feature_outside_bar,
    'engulfing_strength': feature_engulfing_strength,
    # Block ML-10.4: Single Candle Patterns (5 features)
    'doji': feature_doji,
    'hammer': feature_hammer,
    'shooting_star': feature_shooting_star,
    'marubozu': feature_marubozu,
    'spinning_top': feature_spinning_top,
    # Block ML-10.5: Pattern Quality (3 features)
    'pattern_strength': feature_pattern_strength,
    'pattern_confirmation': feature_pattern_confirmation,
    'pattern_divergence': feature_pattern_divergence,
    # Block ML-11: Price Action - Consecutive Days & Swings (6 features)
    'consecutive_green_days': feature_consecutive_green_days,
    'consecutive_red_days': feature_consecutive_red_days,
    'higher_high_10d': feature_higher_high_10d,
    'higher_low_10d': feature_higher_low_10d,
    'swing_low_10d': feature_swing_low_10d,
    'pattern_cluster': feature_pattern_cluster,
    # Block ML-12: Market Regime Indicators (SPY-based) (15 features)
    'market_regime': feature_market_regime,
    'regime_strength': feature_regime_strength,
    'regime_duration': feature_regime_duration,
    'regime_change_probability': feature_regime_change_probability,
    'trending_market_flag': feature_trending_market_flag,
    'choppy_market_flag': feature_choppy_market_flag,
    'bull_market_flag': feature_bull_market_flag,
    'bear_market_flag': feature_bear_market_flag,
    'market_volatility_regime': feature_market_volatility_regime,
    'market_momentum_regime': feature_market_momentum_regime,
    'regime_transition': feature_regime_transition,
    'regime_stability': feature_regime_stability,
    'market_sentiment': feature_market_sentiment,
    'market_fear_greed': feature_market_fear_greed,
    'regime_consistency': feature_regime_consistency,
    # Block ML-13: Market Direction Features (SPY-based) (12 features)
    'market_direction': feature_market_direction,
    'market_direction_strength': feature_market_direction_strength,
    'market_trend_alignment': feature_market_trend_alignment,
    'market_momentum': feature_market_momentum,
    'market_volatility_context': feature_market_volatility_context,
    'market_timing': feature_market_timing,
    'market_support_resistance': feature_market_support_resistance,
    'market_regime_consistency': feature_market_regime_consistency,
    'market_sector_rotation': feature_market_sector_rotation,
    'market_breadth': feature_market_breadth,
    'market_leadership': feature_market_leadership,
    'market_sentiment_alignment': feature_market_sentiment_alignment,
    # Block ML-14: Relative Strength (SPY-based) (12 features)
    'relative_strength_spy': feature_relative_strength_spy,
    'relative_strength_spy_50d': feature_relative_strength_spy_50d,
    'rs_rank_20d': feature_rs_rank_20d,
    'rs_rank_50d': feature_rs_rank_50d,
    'rs_rank_100d': feature_rs_rank_100d,
    'rs_momentum': feature_rs_momentum,
    'outperformance_flag': feature_outperformance_flag,
    'rs_vs_price': feature_rs_vs_price,
    'rs_consistency': feature_rs_consistency,
    'rs_regime': feature_rs_regime,
    'rs_trend': feature_rs_trend,
    'relative_strength_sector': feature_relative_strength_sector,
    # Block ML-15: Time-Based Features (14 features, skipping days_since_earnings)
    'day_of_week': feature_day_of_week,
    'day_of_week_sin': feature_day_of_week_sin,
    'day_of_week_cos': feature_day_of_week_cos,
    'day_of_month': feature_day_of_month,
    'day_of_month_sin': feature_day_of_month_sin,
    'day_of_month_cos': feature_day_of_month_cos,
    'month_of_year': feature_month_of_year,
    'month_of_year_sin': feature_month_of_year_sin,
    'month_of_year_cos': feature_month_of_year_cos,
    'quarter': feature_quarter,
    'is_month_end': feature_is_month_end,
    'is_quarter_end': feature_is_quarter_end,
    'is_year_end': feature_is_year_end,
    'trading_day_of_year': feature_trading_day_of_year,
    # Block ML-16: Statistical Features (15 features, volume_autocorrelation already exists)
    'price_skewness_20d': feature_price_skewness_20d,
    'price_kurtosis_20d': feature_price_kurtosis_20d,
    'returns_skewness_20d': feature_returns_skewness_20d,
    'returns_kurtosis_20d': feature_returns_kurtosis_20d,
    'price_autocorrelation_1d': feature_price_autocorrelation_1d,
    'price_autocorrelation_5d': feature_price_autocorrelation_5d,
    'returns_autocorrelation': feature_returns_autocorrelation,
    # 'volume_autocorrelation': feature_volume_autocorrelation,  # Already exists from earlier block
    'price_variance_ratio': feature_price_variance_ratio,
    'price_half_life': feature_price_half_life,
    'returns_half_life': feature_returns_half_life,
    'price_stationarity': feature_price_stationarity,
    'returns_stationarity': feature_returns_stationarity,
    'price_cointegration': feature_price_cointegration,
    'statistical_regime': feature_statistical_regime,
    # Block ML-17: Advanced Volatility Features (12 features)
    'volatility_skewness': feature_volatility_skewness,
    'volatility_kurtosis': feature_volatility_kurtosis,
    'volatility_autocorrelation': feature_volatility_autocorrelation,
    'volatility_mean_reversion': feature_volatility_mean_reversion,
    'volatility_of_volatility': feature_volatility_of_volatility,
    'volatility_regime_persistence': feature_volatility_regime_persistence,
    'volatility_shock': feature_volatility_shock,
    'volatility_normalized_returns': feature_volatility_normalized_returns,
    'volatility_forecast': feature_volatility_forecast,
    'volatility_term_structure': feature_volatility_term_structure,
    'volatility_risk_premium': feature_volatility_risk_premium,
    'volatility_smoothness': feature_volatility_smoothness,
    # Block ML-18: Advanced Technical Indicators (8 features)
    'bollinger_band_width': feature_bollinger_band_width,
    'fractal_dimension_index': feature_fractal_dimension_index,
    'hurst_exponent': feature_hurst_exponent,
    'price_curvature': feature_price_curvature,
    'aroon_up': feature_aroon_up,
    'aroon_down': feature_aroon_down,
    'aroon_oscillator': feature_aroon_oscillator,
    'donchian_breakout': feature_donchian_breakout,
    # Block ML-19: Market Microstructure Proxies (8 features)
    'liquidity_measure': feature_liquidity_measure,
    'price_impact_proxy': feature_price_impact_proxy,
    'bid_ask_spread_proxy': feature_bid_ask_spread_proxy,
    'order_flow_imbalance': feature_order_flow_imbalance,
    'market_depth_proxy': feature_market_depth_proxy,
    'price_efficiency': feature_price_efficiency,
    'transaction_cost_proxy': feature_transaction_cost_proxy,
    'market_quality': feature_market_quality,
    # Block ML-20: Feature Interactions - Core (20 features)
    'rsi_x_volume': feature_rsi_x_volume,
    'rsi_x_atr': feature_rsi_x_atr,
    'macd_x_volume': feature_macd_x_volume,
    'trend_x_momentum': feature_trend_x_momentum,
    'volume_x_momentum': feature_volume_x_momentum,
    'rsi_x_trend_strength': feature_rsi_x_trend_strength,
    'volatility_x_volume': feature_volatility_x_volume,
    'volatility_x_trend': feature_volatility_x_trend,
    'trend_x_volatility': feature_trend_x_volatility,
    'volatility_x_regime_strength': feature_volatility_x_regime_strength,
    'price_position_x_rsi': feature_price_position_x_rsi,
    'support_resistance_x_momentum': feature_support_resistance_x_momentum,
    'rsi_x_support_distance': feature_rsi_x_support_distance,
    'volume_x_breakout': feature_volume_x_breakout,
    'momentum_x_regime': feature_momentum_x_regime,
    'volume_x_regime': feature_volume_x_regime,
    'rsi_x_relative_strength': feature_rsi_x_relative_strength,
    'trend_x_relative_strength': feature_trend_x_relative_strength,
    'momentum_x_time': feature_momentum_x_time,
    'volume_x_time': feature_volume_x_time,
    # Block ML-21: Predictive Gain Features (15 features)
    'historical_gain_probability': feature_historical_gain_probability,
    'gain_probability_score': feature_gain_probability_score,
    'gain_regime': feature_gain_regime,
    'gain_consistency': feature_gain_consistency,
    'gain_timing': feature_gain_timing,
    'gain_momentum': feature_gain_momentum,
    'gain_acceleration': feature_gain_acceleration,
    'target_distance': feature_target_distance,
    'gain_momentum_strength': feature_gain_momentum_strength,
    'gain_breakout_signal': feature_gain_breakout_signal,
    'gain_risk_ratio': feature_gain_risk_ratio,
    'gain_volume_confirmation': feature_gain_volume_confirmation,
    'gain_trend_alignment': feature_gain_trend_alignment,
    'gain_volatility_context': feature_gain_volatility_context,
    'gain_support_level': feature_gain_support_level,
    # Block ML-22: Accuracy-Enhancing Features (20 features)
    'signal_quality_score': feature_signal_quality_score,
    'signal_strength': feature_signal_strength,
    'signal_consistency': feature_signal_consistency,
    'signal_confirmation': feature_signal_confirmation,
    'signal_timing': feature_signal_timing,
    'signal_risk_reward': feature_signal_risk_reward,
    'signal_statistical_significance': feature_signal_statistical_significance,
    'signal_historical_success': feature_signal_historical_success,
    'signal_ensemble_score': feature_signal_ensemble_score,
    'false_positive_risk': feature_false_positive_risk,
    'signal_divergence': feature_signal_divergence,
    'signal_volume_confirmation': feature_signal_volume_confirmation,
    'signal_trend_alignment': feature_signal_trend_alignment,
    'signal_volatility_context': feature_signal_volatility_context,
    'signal_regime_alignment': feature_signal_regime_alignment,
    'signal_momentum_strength': feature_signal_momentum_strength,
    'signal_support_resistance': feature_signal_support_resistance,
    'signal_relative_strength': feature_signal_relative_strength,
    'signal_multi_timeframe': feature_signal_multi_timeframe,
    'signal_pattern_confirmation': feature_signal_pattern_confirmation,
    # Block ML-23: Market Context (SPY-based) (3 features)
    'mkt_spy_dist_sma200': feature_mkt_spy_dist_sma200,
    'mkt_spy_sma200_slope': feature_mkt_spy_sma200_slope,
    'beta_spy_252d': feature_beta_spy_252d,
    # Block ML-24: Breakout & Channel Features (2 new features, 2 already exist)
    # Note: donchian_position and donchian_breakout already registered above
    'ttm_squeeze_on': feature_ttm_squeeze_on,
    'ttm_squeeze_momentum': feature_ttm_squeeze_momentum,
    # Block ML-25: Trend Exhaustion & Consolidation (4 features)
    'trend_consolidation': feature_trend_consolidation,
    'trend_exhaustion': feature_trend_exhaustion,
    'trend_vs_mean_reversion': feature_trend_vs_mean_reversion,
    'volatility_jump': feature_volatility_jump,
    # Block ML-26.1: Enhanced Volatility Features (10 features)
    'volatility_forecast_accuracy': feature_volatility_forecast_accuracy,
    'volatility_forecast_error': feature_volatility_forecast_error,
    'volatility_forecast_error_true': feature_volatility_forecast_error_true,
    'volatility_forecast_trend': feature_volatility_forecast_trend,
    'volatility_clustering_strength': feature_volatility_clustering_strength,
    'volatility_regime_forecast': feature_volatility_regime_forecast,
    'volatility_surprise': feature_volatility_surprise,
    'volatility_realized_forecast_ratio': feature_volatility_realized_forecast_ratio,
    # Block ML-26.2: Enhanced Gain Probability Features (5 features)
    'gain_probability_trend': feature_gain_probability_trend,
    'gain_probability_consistency_rank': feature_gain_probability_consistency_rank,
    'gain_probability_volatility_adjusted': feature_gain_probability_volatility_adjusted,
    # Block ML-26.3: Distance-Based Rank Features (5 features)
    'dist_support_rank': feature_dist_support_rank,
    # Block ML-26.4: Percentile/Rank Features (8 features)
    'volatility_rank': feature_volatility_rank,
    'return_rank_3m': feature_return_rank_3m,
    'momentum_rank_trend': feature_momentum_rank_trend,
    # Block ML-26.5: Volatility-Volume Interactions (4 features)
    'volatility_volume_correlation': feature_volatility_volume_correlation,
    'volatility_volume_divergence': feature_volatility_volume_divergence,
    'volatility_forecast_volume_confirmation': feature_volatility_forecast_volume_confirmation,
    # Block ML-26.6: Return-Volatility Interactions (3 features)
    'return_volatility_ratio': feature_return_volatility_ratio,
    # Block ML-26.7: Regime Transition Features (3 features)
    'volatility_regime_transition_probability': feature_volatility_regime_transition_probability,
    'gain_regime_transition_probability': feature_gain_regime_transition_probability,
    'momentum_regime_transition': feature_momentum_regime_transition,
    # Block ML-26.8: Composite/Ensemble Features (6 features)
    'top_features_ensemble': feature_top_features_ensemble,
    'volatility_forecast_accuracy_weighted': feature_volatility_forecast_accuracy_weighted,
    'gain_probability_volatility_regime_interaction': feature_gain_probability_volatility_regime_interaction,
    # Block ML-27: Precision-Enhancing Features (5 features)
    'adr_percentage': feature_adr_percentage,
    'distance_from_monthly_vwap': feature_distance_from_monthly_vwap,
    'atr_channel_position': feature_atr_channel_position,
    'vpt_divergence': feature_vpt_divergence,
    'relative_strength_vs_sector': feature_relative_strength_vs_sector,
}


def load_enabled_features(config_path: str):
    """
    Load enabled features from YAML config file.
    
    Args:
        config_path: Path to features.yaml config file
    
    Returns:
        Dictionary mapping feature names to functions
    """
    import yaml
    
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f) or {}
    
    features = config.get('features', {})
    enabled = {}
    
    for name, enabled_flag in features.items():
        if enabled_flag == 1 and name in FEATURE_REGISTRY:
            enabled[name] = FEATURE_REGISTRY[name]
    
    return enabled
